name: Build on Ubuntu

on:
  push:
    branches: [ "feature/*","dev" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Release, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install compiler
      run: |
        sudo apt update
        sudo apt install --fix-missing build-essential cmake git ca-certificates gcc-14 clang-20 libomp-20-dev

    - name: Install deps
      run: | 
        sudo apt install --fix-missing flex libfl-dev libopenmpi-dev paraview-dev libscotch-dev libptscotch-dev libmetis-dev libparmetis-dev libtrilinos-zoltan-dev libboost-all-dev
        
#    - name: Install paraview and related deps
#      run: sudo apt install --fix-missing paraview paraview-dev libvtk9-dev

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G Ninja -DCMAKE_INSTALL_PREFIX=./install -DParaView_TYPE=none -DCMAKE_C_COMPILER=clang-20 -DCMAKE_CXX_COMPILER=clang++-20

    - name: Build
      # Build your program with the given configuration
      run: cmake --build build --parallel

    - name: Install
      run: cmake --install build

    - name: Test secondary development
      run: | 
        cd test/find_package
        cmake -S . -B build -DCMAKE_PREFIX_PATH=$MIKENO_BINARY_INSTALL_PREFIX -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE -DCMAKE_CXX_COMPILER=$WM_CXX
        cmake --build build --parallel

    - name: Test dynamic linking
      run: |
        cd platforms/linux64ClangDPInt32Release
        source FOAMenv.sh
        cmake "-Dsearch_dirs=./bin;./lib" -P ../../cmake/check_linking.cmake

    - name: Run tests
      run: |
        source platforms/linux64ClangDPInt32Release/FOAMenv.sh
        cd test
        ./dictionary/Allrun
        ./fvMeshTools/Allrun
        ./boundaryLayer/Allrun
        ./IO/Allrun
        ./chemistriy/Allrun
        ./multiphaseEuler/Allrun
        

    - name: Run unit test
      run: |
        source platforms/linux64ClangDPInt32Release/FOAMenv.sh
        cd build
        ctest 
