name: Build on Ubuntu

on:
  push:
    branches: [ "feature/*","dev" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Release, RelWithDebInfo, etc.)
  BUILD_TYPE: Release


jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [Gcc, Clang]

    steps:
    - uses: actions/checkout@v4

    - name: Set compiler
      run: |
        echo "foam_platform=linux64${{ matrix.compiler }}DPInt32Opt" >> $GITHUB_ENV
        if ["${{ matrix.compiler }}" == "Gcc"]; then
          echo "c_compiler=gcc-14" >> $GITHUB_ENV
          echo "cxx_compiler=g++-14" >> $GITHUB_ENV
        else
          echo "c_compiler=clang-20" >> $GITHUB_ENV
          echo "cxx_compiler=clang++-20" >> $GITHUB_ENV
        fi
        echo "c_compiler = $c_compiler"
        echo "cxx_compiler = $cxx_compiler"

    - name: Install compiler
      run: |
        sudo apt update
        sudo apt install --fix-missing build-essential cmake git ca-certificates gcc-14 clang-20 libomp-20-dev

    - name: Install deps
      run: | 
        sudo apt install --fix-missing flex libfl-dev libopenmpi-dev paraview-dev libscotch-dev libptscotch-dev libmetis-dev libparmetis-dev libtrilinos-zoltan-dev libboost-all-dev gnuplot
        
#    - name: Install paraview and related deps
#      run: sudo apt install --fix-missing paraview paraview-dev libvtk9-dev

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G Ninja -DParaView_TYPE=none -DCMAKE_C_COMPILER=$c_compiler -DCMAKE_CXX_COMPILER=$cxx_compiler

    - name: Build
      # Build your program with the given configuration
      run: cmake --build build --parallel

    - name: Install
      run: cmake --install build

    - name: Archive
      run: |
        7z a -mx=9 -mmt=0 -snl -sse platform.7z platforms
#        7z a -mx=9 -mmt=0 -xr'!build' -xr'!.git' -xr'!.github' -xr'!idea' -xr'!.vscode' -snl -sse $foam_platform.7z

    - name: Upload archive
      uses: actions/upload-artifact@v4
      with:
        name: platform-binary-${{ matrix.compiler }}
        path: platform.7z
        if-no-files-found: error
        compression-level: 0

    - name: Test secondary development
      run: |
        source platforms/$foam_platform/FOAMenv.sh
        cd test/find_package
        cmake -S . -B build -DCMAKE_PREFIX_PATH=$MIKENO_BINARY_INSTALL_PREFIX -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE -DCMAKE_CXX_COMPILER=$WM_CXX
        cmake --build build --parallel

    - name: Test dynamic linking
      run: |
        cd platforms/$foam_platform
        source FOAMenv.sh
        cmake "-Dsearch_dirs=./bin;./lib" -P ../../cmake/check_linking.cmake

    - name: Prepare for unit test
      run: |
        source platforms/$foam_platform/FOAMenv.sh
        cd tutorials
        blockMesh -case incompressibleFluid/mixerSRF
        blockMesh -case mesh/blockMesh/pipe

    - name: Run unit test
      run: |
        source platforms/$foam_platform/FOAMenv.sh
        cd build/applications/test
        ctest --parallel

    - name: Run function tests
      run: |
        source platforms/$foam_platform/FOAMenv.sh
        export FOAM_SETNAN=set
        export FOAM_SIGFPE=set
        cd test
        chmod +x $(find . -name Allrun)
        chmod +x $(find . -name Allclean)
        ./dictionary/Allrun
        ./dictionary/Allclean
        ./realFluidEOS/Allrun
        ./realFluidEOS/Allclean
        ./fvMeshTools/Allrun
        ./fvMeshTools/Allclean
        ./boundaryLayer/Allrun
        ./boundaryLayer/Allclean
        ./multiphaseEuler/Allrun
        ./multiphaseEuler/Allclean
        ./chemistry/Allrun
        ./chemistry/Allclean
        ./postProcessing/Allrun
        ./postProcessing/Allclean

    - name: Upload test files
      uses: actions/upload-artifact@v4
      if: ${{ failure() }}
      with:
        name: test-failure-files-${{ matrix.compiler }}
        path: test
        compression-level: 7

#    - name: Run unit test
#      run: |
#        source platforms/$foam_platform/FOAMenv.sh
#        cd build
#        ctest
